#spring:
#  profiles:
#    active: @spring.profiles.active@

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: password
    pool-size: 30

server:
  port: 8082